[package]
name = "peekzarr"
version = "0.1.0"
edition = "2024"

[dependencies]
zarrs = "0.19"
viuer = "0.9"
image = "0.25"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
ndarray = "0.16"
