[package]
name = "peekzarr"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
zarrs = "0.23.14"
zarrs_http = "0.3.1"
viuer = { version = "0.11.0", features = ["icy_sixel"] }
image = "0.25.10"
anyhow = "1.0.104"
clap = { version = "4.6.7", features = ["derive"] }
ndarray = "0.17.2"
ndarray-stats = "0.7.0"
noisy_float = "0.2.1"
